In [1]:
import pandas as pd

df = pd.read_csv("students.csv")
df

      name  age  score grade
0    Alice   22   88.5     A
1      Bob   20   73.0     B
2  Charlie   21   91.0     A
3    Diana   23   65.5     C

In [2]:
print(f"Shape : {df.shape}")
print(f"Column names : {df.columns}")
print(f"Data Types : {df.dtypes}")

Shape : (4, 4)
Column names : Index(['name', 'age', 'score', 'grade'], dtype='str')
Data Types : name         str
age        int64
score    float64
grade        str
dtype: object

In [3]:
df.describe()

             age      score
count   4.000000   4.000000
mean   21.500000  79.500000
std     1.290994  12.267844
min    20.000000  65.500000
25%    20.750000  71.125000
50%    21.500000  80.750000
75%    22.250000  89.125000
max    23.000000  91.000000

In [4]:
df1 = df.rename(columns={"score" : "final_score", "grade" : "letter_grade"})
df1[["name","final_score","letter_grade"]]

      name  final_score letter_grade
0    Alice         88.5            A
1      Bob         73.0            B
2  Charlie         91.0            A
3    Diana         65.5            C

In [5]:
df.iloc[0:3,:]

      name  age  score grade
0    Alice   22   88.5     A
1      Bob   20   73.0     B
2  Charlie   21   91.0     A

In [6]:
df.loc[1:3,["name","grade"]]

      name grade
1      Bob     B
2  Charlie     A
3    Diana     C